# Generated by Django 5.0.4 on 2024-04-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('les_app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='product_photos/'),
        ),
    ]
