# Generated by Django 5.0.4 on 2024-05-02 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('les_app2', '0002_product_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.CharField(default=0, max_length=20),
        ),
    ]
